# Infrastructure layer — ORM model.
#
# Define the `games` table. This is the only file that knows about columns.
#
# The Game model should have these columns:
# - id           String, primary key, UUID generated by default
# - title        String, not nullable
# - genre        String, not nullable
# - platform     String, not nullable
# - release_year Integer, nullable
# - cover_url    String, nullable
# - created_at   DateTime, defaults to now (UTC)
#
# Import Base from app.database — do not redefine it here.
from sqlalchemy import Column, String, Integer, DateTime
from datetime import datetime, timezone
import uuid

from app.database import Base


class Game(Base):
    __tablename__ = "games"

    id = Column(
        String,
        primary_key=True,
        default=lambda: str(uuid.uuid4())
    )

    title = Column(
        String,
        nullable=False
    )

    genre = Column(
        String,
        nullable=False
    )

    platform = Column(
        String,
        nullable=False
    )

    release_year = Column(
        Integer,
        nullable=True
    )

    cover_url = Column(
        String,
        nullable=True
    )

    created_at = Column(
        DateTime,
        default=lambda: datetime.now(timezone.utc)
    )
